### ISSUE TITLE
Adding scoped only to given context

### ISSUE THREAD

**Issue by trollfot** [ThirVondukr/aioinject#6]
Hello,

Up until now, I was using Rodi as a DI, mainly for its container API.
I found aioinject great and it suits my needs much better as I don't have to handle the exit stack myself.
However, Rodi allows something that is vital for me : being able to add a local resolution to a context.

Something like:

`
async with container.context() as context:
    ...
    context[SomeClass] = mysingleton     
`

Is it something you would consider adding ? Or do I need to implement it on my own context wrapper ?
Another thing that would be extremely useful, is a method to know if a resolution ever occured.
It allows optional dependencies in my project that I would find very hard to replace.

Thank you

**Comment by ThirVondukr** [comment]
@trollfot I think it would be possible to add an API like this:
```py
context.register(Object(my_singleton))
```
would that work for your use case?
Regarding checking if resolution is occurred - you just want to check if an object was provided? Would you use it in container (global) or context scope?

**Comment by trollfot** [comment]
This kind of API would be perfect, yes.

Regarding the resolution check, it's more about knowing if the constructor was ever called, meaning context.resolve()  was ever called for a given class/factory. Of course, that wouldn't be for the Object, as they are already instanciated.
I use this kind of info to "hook" onto services if they were ever resolved. Not sure if this kind of stuff interest more people or even make sense to anyone else but me.

**Comment by ThirVondukr** [comment]
Currently all instances of objects are kept in `InjectionContext._store._cache`, so providing a public API shouldn't be hard

**Comment by trollfot** [comment]
Sounds very promising :+1:

**Comment by ThirVondukr** [comment]
Having a second thought about providing a public API for checking if a dependency was ever resolved - do you need to check that for each context or just globally?
I was thinking that maybe an extension could be used here, e.g.
```py
class SomeExtension(OnResolveExtension):
    async def on_resolve(self, ...) -> None: ...
```
(OnResolveExtension) doesn't exist right now 😉

**Comment by trollfot** [comment]
I use this to check if a given service was instanciated in a context, to hook stuff onto it.
If you think it's an anti pattern, I'll find some other solution to work around it.

**Comment by ThirVondukr** [comment]
I don't think this is an antipattern, seems like a valid use case for it, I'm just thinking of ways to do that without doing any changes to any internals, so an extension sounds good to me. Maybe a list of context extensions could be provided when instantiating said context?
```py
track_resolves = TrackResolveExtension() # Custom class

with container.context(extensions=(track_resolves, ) as ctx:
    ...
    if track_resolves.provided_types:  # Or any other api you want
        ...
```
I'd imagine this should be easy to implement:
```py
class TrackResolveExtension:
    def __init__(self) -> None:
        self.provided_types = set()

    async def on_resolve(self, type: type[object]) -> None:
        self.provided_types.add(type)
 ```

**Comment by trollfot** [comment]
I can work with that, it looks very flexible

**Comment by ThirVondukr** [comment]
@trollfot Could you pip install `git+https://github.com/ThirVondukr/aioinject.git@1f41018985f818ca0d88fe3b17024c53169c0083`?

**Comment by ThirVondukr** [comment]
https://github.com/ThirVondukr/aioinject/commit/981cb08f0ea0b9edafb93e4334caf80949e00a79
https://github.com/ThirVondukr/aioinject/commit/1f41018985f818ca0d88fe3b17024c53169c0083

**Comment by trollfot** [comment]
The registration seems to work fine. I need to test the on_resolve extension bit next.
Thank you very much for your very quick response and help.
I hope these additions will be useful  to others 😄

**Comment by ThirVondukr** [comment]
I added extensions in 0.30.0 release, but seems like package uploads are temporarily suspended on PyPi

**Comment by trollfot** [comment]
Oh, great, thank you so much.
Yeah, I saw that pypi was having some troubles.

**Comment by trollfot** [comment]
Maybe we can close this issue, now :)
